# Generated by Django 5.0.3 on 2024-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=23, max_length=150),
            preserve_default=False,
        ),
    ]
