# Generated by Django 5.0.3 on 2024-03-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=255)),
                ('pv', models.TextField()),
                ('transformer', models.TextField()),
                ('hourlyData', models.TextField()),
                ('dailyData', models.TextField()),
                ('monthlyData', models.TextField()),
                ('dashBoard', models.TextField()),
                ('warning', models.TextField()),
                ('history', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
