# Generated by Django 5.0.3 on 2024-03-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='power',
            field=models.TextField(default=500),
            preserve_default=False,
        ),
    ]
