# Generated by Django 5.0.3 on 2024-03-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_password',
            field=models.CharField(default=100, max_length=255),
            preserve_default=False,
        ),
    ]
